//
// Generated file, do not edit! Created by opp_msgc 4.1 from messages/ConnectionEvent.msg.
//

#ifndef _CONNECTIONEVENT_M_H_
#define _CONNECTIONEVENT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/ConnectionEvent.msg</tt> by opp_msgc.
 * <pre>
 * message ConnectionEvent {
 *     int in;
 *     int out;
 * }
 * </pre>
 */
class ConnectionEvent : public ::cMessage
{
  protected:
    int in_var;
    int out_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConnectionEvent&);

  public:
    ConnectionEvent(const char *name=NULL, int kind=0);
    ConnectionEvent(const ConnectionEvent& other);
    virtual ~ConnectionEvent();
    ConnectionEvent& operator=(const ConnectionEvent& other);
    virtual ConnectionEvent *dup() const {return new ConnectionEvent(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getIn() const;
    virtual void setIn(int in_var);
    virtual int getOut() const;
    virtual void setOut(int out_var);
};

inline void doPacking(cCommBuffer *b, ConnectionEvent& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ConnectionEvent& obj) {obj.parsimUnpack(b);}


#endif // _CONNECTIONEVENT_M_H_
